pipeline {
    
    agent any 
       
    stages {
        
        stage('Checkout'){
           steps {
               sh 'echo passed'
               // git branch: 'main', url: 'https://github.com/KUMAR-REDDY-BAVANASI/Jenkins-Zero-To-Hero.git'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    cd python-jenkins-argocd-k8s/
                    docker build -t kumar5483/cicd-todos:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker push kumar5483/cicd-todos:${BUILD_NUMBER}
                    '''
                }
            }
        }
             
        stage('Update K8S manifest & push to Repo'){
            steps {
                withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                    sh '''
                        cat python-jenkins-argocd-k8s/deploy/deploy.yaml
                        sed -i '' "s/replaceImageTag/${BUILD_NUMBER}/g" python-jenkins-argocd-k8s/deploy/deploy.yaml
                        cat python-jenkins-argocd-k8s/deploy/deploy.yaml
                        git add python-jenkins-argocd-k8s/deploy/deploy.yaml
                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                        git remote -v
                        git push https://github.com/KUMAR-REDDY-BAVANASI/cicd-demo-manifests-repo.git HEAD:main
                        '''
                }
            }
        }
    }
    post { 
        always { 
            cleanWs()
        }
    }
}
